#root -l 'checkflipbit.cxx("/home/pixeldaq/cyric/afterIrrad/src/registerdata/run00052_PR00042.txt")'
#root -l 'checkflipbit.cxx("/home/pixeldaq/cyric/afterIrrad/src/registerdata/run00051_PR00040.txt")'
#root -l 'checkflipbit.cxx("/home/pixeldaq/cyric/afterIrrad/src/registerdata/run00047_PR00037.txt")'
root -l 'checkflipbit.cxx("/home/pixeldaq/cyric/afterIrrad/src/registerdata/run00041_PR00029.txt")'
#root -l 'checkflipbitberB.cxx("/home/pixeldaq/cyric/afterIrrad/src/registerdata/run00047_PR00001.txt")'
